$ios_deployment_target = '14.0'
$watchos_deployment_target = '8.0'
use_frameworks!
inhibit_all_warnings!

def default_pods 
  pod 'Sourcery'
end

target 'petWalk' do
  platform :ios, $deployment_target
  default_pods

  target 'petWalkTests' do
    inherit! :search_paths
  end

  target 'petWalkUITests' do
    inherit! :search_paths
  end

end

target 'petWalk WatchKit App' do
  platform :watchos, $watchos_deployment_target
end 

target 'petWalk WatchKit Extension' do
  platform :watchos, $watchos_deployment_target
  default_pods

  target 'petWalk WatchKit AppTests' do
    inherit! :search_paths
    default_pods
  end

  target 'petWalk WatchKit AppUITests' do
    inherit! :search_paths
  end
end