platform :ios, '14.0'

def default_pods 
  pod 'Sourcery'
end

target 'petWalk' do
  use_frameworks!
  default_pods

  target 'petWalk WatchKit AppTests' do
    inherit! :search_paths
    default_pods
  end

  target 'petWalk WatchKit AppUITests' do
  end

  target 'petWalkTests' do
    inherit! :search_paths
  end

  target 'petWalkUITests' do
  end

end

# target 'petWalk WatchKit App' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for petWalk WatchKit App

#   target 'petWalk WatchKit AppTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

#   target 'petWalk WatchKit AppUITests' do
#     # Pods for testing
#   end

# end

# target 'petWalk WatchKit Extension' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for petWalk WatchKit Extension

# end
